[project]
name = "memory-store"
version = "0.1.0"
description = "Ephemeral, per-charter memory store (kNN + Concept Index) for browser research"
authors = [{ name = "BRT" }]
requires-python = ">=3.10"
readme = "README.md"
keywords = ["retrieval", "embeddings", "concept-index", "browser-research"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
